[svn-r499] enabled VPATH build by setting TEXINPUTS/BIBINPUTS so latex/bibtext/dvipdfm can locate remote source files.  Removed symbol link hacks

diff --git a/doc/refman/Makefile.in b/doc/refman/Makefile.in
--- a/doc/refman/Makefile.in
+++ b/doc/refman/Makefile.in
@@ -8,26 +8,31 @@ prefix          = @prefix@
 docdir          = @docdir@
 srcdir = @srcdir@
 
-VPATH = .:@srcdir@
+@VPATH@
+
+LATEX      = export TEXINPUTS=".:$(srcdir):" ; latex
+BIBTEX     = export BIBINPUTS=".:$(srcdir):" ; bibtex
+DVIPDFM    = export TEXINPUTS=".:$(srcdir):" ; dvipdfm
+LATEX2HTML = latex2html
 
 MPIMANAUXFILES = refman.sty tpage.sty refcmd.tex refmpi.tex
 mpiman.dvi: mpiman.tex MPI_Wtime.tex
 	-rm -f mpiman.log mpiman.msg
-	for file in $(MPIMANAUXFILES) ; do \
-	    if [ ! -s $$file ] ; then \
-	       if [ -s $(srcdir)/$$file ] ; then \
-	            cp $(srcdir)/$$file . ; \
-               else \
-		    echo "Unable to find file $$file" ; \
-		    exit 1; \
-               fi ;\
-	    fi ; \
-	done
-	-latex $(srcdir)/mpiman < /dev/null 2>&1 >mpiman.msg
-	latex $(srcdir)/mpiman < /dev/null 2>&1 >mpiman.msg
+# 	for file in $(MPIMANAUXFILES) ; do \
+# 	    if [ ! -s $$file ] ; then \
+# 	       if [ -s $(srcdir)/$$file ] ; then \
+# 	            cp $(srcdir)/$$file . ; \
+#                else \
+# 		    echo "Unable to find file $$file" ; \
+# 		    exit 1; \
+#                fi ;\
+# 	    fi ; \
+# 	done
+	-$(LATEX) $(srcdir)/mpiman < /dev/null 2>&1 >mpiman.msg
+	$(LATEX) $(srcdir)/mpiman < /dev/null 2>&1 >mpiman.msg
 
 mpiman.pdf: mpiman.dvi
-	dvipdfm mpiman
+	$(DVIPDFM) mpiman
 
 clean:
 	rm -f *.dvi *.log *.toc *.aux *.out
