[svn-r241] fixed make dist-with-version so it works correctly when tag is HEAD

diff --git a/Makefile.sm b/Makefile.sm
--- a/Makefile.sm
+++ b/Makefile.sm
@@ -137,7 +137,12 @@ dist-with-version:
 	@echo ""; echo "Cutting version ${version} of the MPICH2 distribution from tag ${tag}" ; echo ""
 	if [ ! -d tmpdir ] ; then mkdir tmpdir ; fi 
 	rm -f svnexp.log 
-	( cd tmpdir && svn export $(MPISVNHOME)/mpich2/tags/release/${tag} mpich2 > svnexp.log 2>&1 ) || (echo "svn export failed; see tmpdir/svnexp.log" && exit 1 )
+	if [ "$(tag)" == HEAD ] ; then
+	    URL=$(MPISVNHOME)/mpich2/trunk
+	else
+	    URL=$(MPISVNHOME)/mpich2/tags/release/${tag}
+	fi
+	( cd tmpdir && svn export $(URL) mpich2 > svnexp.log 2>&1 ) || (echo "svn export failed; see tmpdir/svnexp.log" && exit 1 )
 	( cd tmpdir/mpich2 && sed -e "s/^VERSION = .*/VERSION = ${version}/" Makefile.sm >.tmp && mv .tmp Makefile.sm )
 	echo "${version}" >tmpdir/mpich2/maint/Version
 	mv tmpdir/mpich2 tmpdir/${PACKAGE}-${version}
