[svn-synthetic] tags/release/mpich2-1.0.8

diff --git a/src/env/mpicxx.bash.in b/src/env/mpicxx.bash.in
--- a/src/env/mpicxx.bash.in
+++ b/src/env/mpicxx.bash.in
@@ -161,8 +161,18 @@ for arg in "$@" ; do
     addarg=no
     # Loading the profConf file is handled below
     ;;
-	# -help
     -help)
+    NC=`echo "$CXX" | sed 's%\/% %g' | awk '{print $NF}' -`
+    if [ -f "$sysconfdir/mpixxx_opts.conf" ] ; then
+        . $sysconfdir/mpixxx_opts.conf
+        echo "    -cxx=xxx      - Reset the native compiler to xxx."
+    else
+        if [ -f "./mpixxx_opts.conf" ] ; then
+            . ./mpixxx_opts.conf
+            echo "    -cxx=xxx      - Reset the native compiler to xxx."
+        fi
+    fi
+    exit 0
     ;;
     *)
     ;;
@@ -174,6 +184,12 @@ for arg in "$@" ; do
     # Some versions of bash do not accept ((argno++))
     argno=`expr $argno + 1`
 done
+
+if [ $# -eq 0 ] ; then
+    echo "Error: Command line argument is needed!"
+    "$0" -help
+    exit 1
+fi
 
 # -----------------------------------------------------------------------
 # Derived variables.  These are assembled from variables set from the
diff --git a/src/env/mpif77.in b/src/env/mpif77.in
--- a/src/env/mpif77.in
+++ b/src/env/mpif77.in
@@ -167,8 +167,20 @@ for arg in "$@" ; do
     addarg=no
     # Loading the profConf file is handled below
     ;;
-	# -help
     -help)
+    NC=`echo "$FC" | sed 's%\/% %g' | awk '{print $NF}' -`
+    if [ -f "$sysconfdir/mpixxx_opts.conf" ] ; then
+        . $sysconfdir/mpixxx_opts.conf
+        echo "    -f77=xxx      - Reset the native compiler to xxx."
+        echo "    -fc=xxx       - Reset the native compiler to xxx."
+    else
+        if [ -f "./mpixxx_opts.conf" ] ; then
+            . ./mpixxx_opts.conf
+            echo "    -f77=xxx      - Reset the native compiler to xxx."
+            echo "    -fc=xxx       - Reset the native compiler to xxx."
+        fi
+    fi
+    exit 0
     ;;
         # -----------------------------------------------------------------
 	# Other arguments.  We are careful to handle arguments with 
@@ -245,6 +257,12 @@ for arg in "$@" ; do
         allargs="$allargs $qarg"
     fi
 done
+
+if [ $# -eq 0 ] ; then
+    echo "Error: Command line argument is needed!"
+    "$0" -help
+    exit 1
+fi
 
 # -----------------------------------------------------------------------
 # Derived variables.  These are assembled from variables set from the
diff --git a/src/mpid/ch3/channels/nemesis/setup_channel b/src/mpid/ch3/channels/nemesis/setup_channel
--- a/src/mpid/ch3/channels/nemesis/setup_channel
+++ b/src/mpid/ch3/channels/nemesis/setup_channel
@@ -27,12 +27,29 @@ fi
 
 pathlist=""
 pathlist="$pathlist src/mpid/${device_name}/channels/${channel_name}/include"
+pathlist="$pathlist src/mpid/common/locks"
 for path in $pathlist ; do
     #CPPFLAGS="$CPPFLAGS -I${master_top_builddir}/${path}"
     #CPPFLAGS="$CPPFLAGS -I${master_top_srcdir}/${path}"
     MPICH2_INCLUDE_FLAGS="$MPICH2_INCLUDE_FLAGS -I${master_top_builddir}/${path} -I${master_top_srcdir}/${path}"
 done
 
+devsubsystems="$devsubsystems src/mpid/common/locks"
+CPPFLAGS="$CPPFLAGS -DUSE_PROCESS_LOCKS"
+
+dir=${master_top_srcdir}/src/mpid/common/locks
+if test ! -d $dir ; then
+    echo "ERROR: ${dir} does not exist"
+    exit 1
+fi
+file=${dir}/setup
+if test -f $file ; then
+    echo sourcing $file
+    . $file
+else
+    echo "Cannot find $file , needed to build process locks"
+    exit 1
+fi
 
 # include prototype
 prototype_dir=${master_top_srcdir}/src/mpid/${device_name}/channels/${channel_name}/nemesis
