[svn-r9380] Moved the autoreconf test before its use on checking individual autotools added in r9262.

diff --git a/maint/updatefiles b/maint/updatefiles
--- a/maint/updatefiles
+++ b/maint/updatefiles
@@ -359,11 +359,77 @@ else
     echo "	automake is in $automakedir"
     echo "	libtool  is in $libtooldir"
     # Emit a big warning message if $same_atdir = no.
-    warn "Experimental support of autotools being in different locations."
-    warn "Configure or even make may fail in some unexpected ways."
+    warn "Autotools are in different locations. In rare occasion,"
+    warn "resulting configure or makefile may fail in some unexpected ways."
 fi
 
+########################################################################
+## Check if autoreconf can be patched to work
+## when autotools are not in the same location.
+## This test needs to be done before individual tests of autotools
+########################################################################
 
+# If autotools are not in the same location, override autoreconf appropriately.
+if [ "$same_atdir" != "yes" ] ; then
+    if [ -z "$libtooldir" ] ; then
+        ProgHomeDir $libtoolize libtooldir
+    fi
+    libtoolm4dir="$libtooldir/share/aclocal"
+    echo_n "Checking if $autoreconf accepts -I $libtoolm4dir... "
+    new_autoreconf_works=no
+    if [ -d "$libtoolm4dir" -a -f "$libtoolm4dir/libtool.m4" ] ; then
+        recreate_tmp
+        cat >.tmp/configure.ac <<_EOF
+AC_INIT(foo,1.0)
+AC_PROG_LIBTOOL
+AC_OUTPUT
+_EOF
+        AUTORECONF="$autoreconf -I $libtoolm4dir"
+        if (cd .tmp && $AUTORECONF -ivf >/dev/null 2>&1) ; then
+            new_autoreconf_works=yes
+        fi
+        rm -rf .tmp
+    fi
+    echo "$new_autoreconf_works"
+    # If autoreconf accepts -I <libtool's m4 dir> correctly, use -I.
+    # If not, run libtoolize before autoreconf (i.e. for autoconf <= 2.63)
+    # This test is more general than checking the autoconf version.
+    if [ "$new_autoreconf_works" != "yes" ] ; then
+        echo_n "Checking if $autoreconf works after an additional $libtoolize step... "
+        new_autoreconf_works=no
+        recreate_tmp
+        # Need AC_CONFIG_
+        cat >.tmp/configure.ac <<_EOF
+AC_INIT(foo,1.0)
+AC_CONFIG_AUX_DIR([m4])
+AC_CONFIG_MACRO_DIR([m4])
+AC_PROG_LIBTOOL
+AC_OUTPUT
+_EOF
+        cat >.tmp/Makefile.am <<_EOF
+ACLOCAL_AMFLAGS = -I m4
+_EOF
+        AUTORECONF="eval $libtoolize && $autoreconf"
+        if (cd .tmp && $AUTORECONF -ivf >u.txt 2>&1) ; then
+            new_autoreconf_works=yes
+        fi
+        rm -rf .tmp
+        echo "$new_autoreconf_works"
+    fi
+    if [ "$new_autoreconf_works" = "yes" ] ; then
+        export AUTORECONF
+        autoreconf="$AUTORECONF"
+    else
+        # Since all autoreconf workarounds do not work, we need
+        # to require all autotools to be in the same directory.
+        do_atdir_check=yes
+        error "Since none of the autoreconf workaround works"
+        error "and autotools are not in the same directory, aborting..."
+        error "Updating autotools or putting all autotools in the same location"
+        error "may resolve the issue."
+        exit 1
+    fi
+fi
 
 ########################################################################
 ## Verify autoconf version
@@ -487,73 +553,6 @@ EOF
     exit 1
 fi
 
-
-########################################################################
-## Check if autoreconf can be patched to work
-## when autotools are not in the same location.
-########################################################################
-
-# If autotools are not in the same location, override autoreconf appropriately.
-if [ "$same_atdir" != "yes" ] ; then
-    if [ -z "$libtooldir" ] ; then
-        ProgHomeDir $libtoolize libtooldir
-    fi
-    libtoolm4dir="$libtooldir/share/aclocal"
-    echo_n "Checking if $autoreconf accepts -I $libtoolm4dir... "
-    new_autoreconf_works=no
-    if [ -d "$libtoolm4dir" -a -f "$libtoolm4dir/libtool.m4" ] ; then
-        recreate_tmp
-        cat >.tmp/configure.ac <<_EOF
-AC_INIT(foo,1.0)
-AC_PROG_LIBTOOL
-AC_OUTPUT
-_EOF
-        AUTORECONF="$autoreconf -I $libtoolm4dir"
-        if (cd .tmp && $AUTORECONF -ivf >/dev/null 2>&1) ; then
-            new_autoreconf_works=yes
-        fi
-        rm -rf .tmp
-    fi
-    echo "$new_autoreconf_works"
-    # If autoreconf accepts -I <libtool's m4 dir> correctly, use -I.
-    # If not, run libtoolize before autoreconf (i.e. for autoconf <= 2.63)
-    # This test is more general than checking the autoconf version.
-    if [ "$new_autoreconf_works" != "yes" ] ; then
-        echo_n "Checking if $autoreconf works after an additional $libtoolize step... "
-        new_autoreconf_works=no
-        recreate_tmp
-        # Need AC_CONFIG_
-        cat >.tmp/configure.ac <<_EOF
-AC_INIT(foo,1.0)
-AC_CONFIG_AUX_DIR([m4])
-AC_CONFIG_MACRO_DIR([m4])
-AC_PROG_LIBTOOL
-AC_OUTPUT
-_EOF
-        cat >.tmp/Makefile.am <<_EOF
-ACLOCAL_AMFLAGS = -I m4
-_EOF
-        AUTORECONF="eval $libtoolize && $autoreconf"
-        if (cd .tmp && $AUTORECONF -ivf >u.txt 2>&1) ; then
-            new_autoreconf_works=yes
-        fi
-        rm -rf .tmp
-        echo "$new_autoreconf_works"
-    fi
-    if [ "$new_autoreconf_works" = "yes" ] ; then
-        export AUTORECONF
-        autoreconf="$AUTORECONF"
-    else
-        # Since all autoreconf workarounds do not work, we need
-        # to require all autotools to be in the same directory.
-        do_atdir_check=yes
-        error "Since none of the autoreconf workaround works"
-        error "and autotools are not in the same directory, aborting..."
-        error "Updating autotools or putting all autotools in the same location"
-        error "may resolve the issue."
-        exit 1
-    fi
-fi
 
 ########################################################################
 ## Checking for UNIX find
