[svn-r9379] fixed the autoconf version test (using autoreconf added in r9262) that uses AC_PREREQ() without AC_INIT.

diff --git a/maint/updatefiles b/maint/updatefiles
--- a/maint/updatefiles
+++ b/maint/updatefiles
@@ -372,8 +372,27 @@ fi
 echo_n "Checking for autoconf version... "
 recreate_tmp
 ver=2.67
+# petsc.mcs.anl.gov's /usr/bin/autoreconf is version 2.65 which returns OK
+# if configure.in has AC_PREREQ() withOUT AC_INIT.
+#
+# ~/> hostname
+# petsc
+# ~> /usr/bin/autoconf --version
+# autoconf (GNU Autoconf) 2.65
+# ....
+# ~/> cat configure.ac
+# AC_PREREQ(2.68)
+# ~/> /usr/bin/autoconf ; echo "rc=$?"
+# configure.ac:1: error: Autoconf version 2.68 or higher is required
+# configure.ac:1: the top level
+# autom4te: /usr/bin/m4 failed with exit status: 63
+# rc=63
+# ~/> /usr/bin/autoreconf ; echo "rc=$?"
+# rc=0
 cat > .tmp/configure.in<<EOF
+AC_INIT
 AC_PREREQ($ver)
+AC_OUTPUT
 EOF
 if (cd .tmp && $autoreconf $autoreconf_args >/dev/null 2>&1 ) ; then
     echo ">= $ver"
