hwloc: update to 1.11.4
Signed-off-by: Sangmin Seo <sseo@anl.gov>

diff --git a/src/pm/hydra/tools/topo/hwloc/hwloc/doc/Makefile.am b/src/pm/hydra/tools/topo/hwloc/hwloc/doc/Makefile.am
--- a/src/pm/hydra/tools/topo/hwloc/hwloc/doc/Makefile.am
+++ b/src/pm/hydra/tools/topo/hwloc/hwloc/doc/Makefile.am
@@ -1,6 +1,6 @@
-# Copyright © 2009-2014 Inria.  All rights reserved.
+# Copyright © 2009-2016 Inria.  All rights reserved.
 # Copyright © 2009-2013 Université Bordeaux
-# Copyright © 2009-2010 Cisco Systems, Inc.  All rights reserved.
+# Copyright © 2009-2016 Cisco Systems, Inc.  All rights reserved.
 # See COPYING in top-level directory.
 
 AM_CPPFLAGS = $(HWLOC_CPPFLAGS)
@@ -193,8 +193,23 @@ doc: $(DOX_TAG) $(DOX_LETTERPDF) $(DOX_A4PDF)
 
 else !HWLOC_BUILD_DOXYGEN
 
-# When we don't have doxygen, nothing to do
+# When we don't have doxygen, nothing to do for a normal build
 doc:
+
+if !HWLOC_INSTALL_DOXYGEN
+# But if the user tries to "make dist" and doesn't have all the right
+# tools, and prebuilt doc aren't available, fail with a helpful error
+$(BUILT_IMAGES) $(DOX_A4PDF) $(DOX_LETTERPDF):
+	@echo " "
+	@echo "*** ERROR: You do not have all the documentation generation tools"
+	@echo "*** that hwloc needs.  Check the output from when you ran 'configure'"
+	@echo "*** (in section \"Configuring hwloc documentation\") to see what tools"
+	@echo "*** you are missing."
+	@echo "***"
+	@echo "*** 'make' will now abort with an error."
+	@echo " "
+	@exit 1
+endif !HWLOC_INSTALL_DOXYGEN
 
 endif !HWLOC_BUILD_DOXYGEN
 # there are also a bunch of doxygen-build-dependencies later in this file
@@ -259,7 +274,6 @@ man3_object_types_DATA = \
         $(DOX_MAN_DIR)/man3/HWLOC_OBJ_PCI_DEVICE.3 \
         $(DOX_MAN_DIR)/man3/HWLOC_OBJ_PACKAGE.3 \
         $(DOX_MAN_DIR)/man3/HWLOC_OBJ_SYSTEM.3 \
-        $(DOX_MAN_DIR)/man3/HWLOC_OBJ_TYPE_MAX.3 \
         $(DOX_MAN_DIR)/man3/hwloc_obj_type_t.3 \
         $(DOX_MAN_DIR)/man3/HWLOC_OBJ_CACHE_UNIFIED.3 \
         $(DOX_MAN_DIR)/man3/HWLOC_OBJ_CACHE_DATA.3 \
@@ -364,10 +378,13 @@ man3_object_stringsdir = $(man3dir)
 man3_object_strings_DATA = \
         $(DOX_MAN_DIR)/man3/hwlocality_object_strings.3 \
         $(DOX_MAN_DIR)/man3/hwloc_obj_type_string.3 \
-        $(DOX_MAN_DIR)/man3/hwloc_obj_type_sscanf.3 \
         $(DOX_MAN_DIR)/man3/hwloc_obj_type_snprintf.3 \
         $(DOX_MAN_DIR)/man3/hwloc_obj_attr_snprintf.3 \
         $(DOX_MAN_DIR)/man3/hwloc_obj_cpuset_snprintf.3 \
+        $(DOX_MAN_DIR)/man3/hwloc_obj_type_sscanf.3
+
+man3_object_info_attrsdir = $(man3dir)
+man3_object_info_attrs_DATA = \
         $(DOX_MAN_DIR)/man3/hwloc_obj_get_info_by_name.3 \
         $(DOX_MAN_DIR)/man3/hwloc_obj_add_info.3
 
@@ -399,6 +416,7 @@ man3_membinding_DATA = \
         $(DOX_MAN_DIR)/man3/HWLOC_MEMBIND_MIXED.3 \
         $(DOX_MAN_DIR)/man3/HWLOC_MEMBIND_NEXTTOUCH.3 \
         $(DOX_MAN_DIR)/man3/HWLOC_MEMBIND_NOCPUBIND.3 \
+        $(DOX_MAN_DIR)/man3/HWLOC_MEMBIND_BYNODESET.3 \
         $(DOX_MAN_DIR)/man3/HWLOC_MEMBIND_PROCESS.3 \
         $(DOX_MAN_DIR)/man3/HWLOC_MEMBIND_REPLICATE.3 \
         $(DOX_MAN_DIR)/man3/HWLOC_MEMBIND_STRICT.3 \
@@ -417,6 +435,7 @@ man3_membinding_DATA = \
         $(DOX_MAN_DIR)/man3/hwloc_set_area_membind_nodeset.3  \
         $(DOX_MAN_DIR)/man3/hwloc_get_area_membind.3 \
         $(DOX_MAN_DIR)/man3/hwloc_get_area_membind_nodeset.3  \
+        $(DOX_MAN_DIR)/man3/hwloc_get_area_memlocation.3 \
         $(DOX_MAN_DIR)/man3/hwloc_alloc.3 \
         $(DOX_MAN_DIR)/man3/hwloc_alloc_membind.3 \
         $(DOX_MAN_DIR)/man3/hwloc_alloc_membind_nodeset.3  \
@@ -715,6 +734,7 @@ $(man3_creation_DATA): $(DOX_TAG)
 $(man3_configuration_DATA): $(DOX_TAG)
 $(man3_levels_DATA): $(DOX_TAG)
 $(man3_object_strings_DATA): $(DOX_TAG)
+$(man3_object_info_attrs_DATA): $(DOX_TAG)
 $(man3_cpubinding_DATA): $(DOX_TAG)
 $(man3_membinding_DATA): $(DOX_TAG)
 $(man3_tinker_DATA): $(DOX_TAG)
@@ -783,8 +803,11 @@ $(HWLOC_top_srcdir)/README: $(DOX_TAG)
 	sed -n -f $(srcdir)/README.sed $(DOX_HTML_DIR)/index.html > $(DOX_HTML_README)
 	LC_ALL=C $(HWLOC_W3_GENERATOR) $(DOX_HTML_README) \
 	 | $(SED) -n -e 's/^   //' -e '/^Introduction$$/,$$p' \
-	 | $(SED) -e '/^--*-$$/,$$ d' \
+	 | $(SED) -e '/^Installation$$/,$$ d' \
 	 > $@
+	echo >> $@
+	echo >> $@
+	echo "See https://www.open-mpi.org/projects/hwloc/doc/ for more hwloc documentation." >> $@
 	rm -f $(DOX_HTML_README)
 
 else
